# Generated by Django 5.1.2 on 2026-05-16 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification', max_length=255)),
                ('message', models.TextField(default='')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Nouvelle tâche'), ('TASK_UPDATED', 'Tâche mise à jour'), ('COMMENT_ADDED', 'Nouveau commentaire'), ('INVITATION_RECEIVED', 'Invitation reçue'), ('INVITATION_ACCEPTED', 'Invitation acceptée'), ('PROJECT_UPDATED', 'Projet mis à jour'), ('MENTION', 'Mention'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
