# Generated by Django 5.1.2 on 2026-05-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROJECT_CREATED', 'Projet créé'), ('PROJECT_UPDATED', 'Projet mis à jour'), ('TASK_CREATED', 'Tâche créée'), ('TASK_UPDATED', 'Tâche mise à jour'), ('MEMBER_ADDED', 'Membre ajouté'), ('MEMBER_REMOVED', 'Membre retiré'), ('COMMENT_ADDED', 'Commentaire ajouté'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('target_description', models.TextField(default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
