spring:
  datasource:
    url: ${PROD_DATASOURCE_URL:jdbc:mysql://localhost:3306/collabsme?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_DATASOURCE_USERNAME:root}
    password: ${PROD_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    show-sql: false

app:
  upload:
    dir: ${UPLOAD_DIR:/var/data/collabsme/uploads}
